[2022-09-03T11:32:38.462+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: weather_data.check_weather_mkp manual__2022-09-03T11:32:37.489079+00:00 [queued]>
[2022-09-03T11:32:38.468+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: weather_data.check_weather_mkp manual__2022-09-03T11:32:37.489079+00:00 [queued]>
[2022-09-03T11:32:38.469+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-03T11:32:38.470+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-03T11:32:38.471+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-03T11:32:38.478+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): check_weather_mkp> on 2022-09-03 11:32:37.489079+00:00
[2022-09-03T11:32:38.482+0000] {standard_task_runner.py:52} INFO - Started process 10362 to run task
[2022-09-03T11:32:38.485+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_data', 'check_weather_mkp', 'manual__2022-09-03T11:32:37.489079+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpzv88e1wv', '--error-file', '/tmp/tmp2726g0lw']
[2022-09-03T11:32:38.486+0000] {standard_task_runner.py:80} INFO - Job 187: Subtask check_weather_mkp
[2022-09-03T11:32:38.537+0000] {task_command.py:371} INFO - Running <TaskInstance: weather_data.check_weather_mkp manual__2022-09-03T11:32:37.489079+00:00 [running]> on host 3d56073112d8
[2022-09-03T11:32:38.588+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data
AIRFLOW_CTX_TASK_ID=check_weather_mkp
AIRFLOW_CTX_EXECUTION_DATE=2022-09-03T11:32:37.489079+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-03T11:32:37.489079+00:00
[2022-09-03T11:32:38.599+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dag.py", line 19, in context_handler
    response = json.loads(ti.xcom_pull(task_ids='getting_weather_krd'))
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2022-09-03T11:32:38.609+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=weather_data, task_id=check_weather_mkp, execution_date=20220903T113237, start_date=20220903T113238, end_date=20220903T113238
[2022-09-03T11:32:38.622+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 187 for task check_weather_mkp (the JSON object must be str, bytes or bytearray, not NoneType; 10362)
[2022-09-03T11:32:38.658+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-03T11:32:38.678+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
