[2022-09-03T11:25:20.114+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: weather_data.insert_weather_krd manual__2022-09-03T11:25:14.233214+00:00 [queued]>
[2022-09-03T11:25:20.121+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: weather_data.insert_weather_krd manual__2022-09-03T11:25:14.233214+00:00 [queued]>
[2022-09-03T11:25:20.123+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-03T11:25:20.124+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-03T11:25:20.125+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-03T11:25:20.135+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): insert_weather_krd> on 2022-09-03 11:25:14.233214+00:00
[2022-09-03T11:25:20.139+0000] {standard_task_runner.py:52} INFO - Started process 9922 to run task
[2022-09-03T11:25:20.142+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_data', 'insert_weather_krd', 'manual__2022-09-03T11:25:14.233214+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmph3lc4twy', '--error-file', '/tmp/tmpon9_gavi']
[2022-09-03T11:25:20.144+0000] {standard_task_runner.py:80} INFO - Job 149: Subtask insert_weather_krd
[2022-09-03T11:25:20.193+0000] {task_command.py:371} INFO - Running <TaskInstance: weather_data.insert_weather_krd manual__2022-09-03T11:25:14.233214+00:00 [running]> on host 3d56073112d8
[2022-09-03T11:25:20.249+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data
AIRFLOW_CTX_TASK_ID=insert_weather_krd
AIRFLOW_CTX_EXECUTION_DATE=2022-09-03T11:25:14.233214+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-03T11:25:14.233214+00:00
[2022-09-03T11:25:20.257+0000] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-09-03T11:25:20.261+0000] {sql.py:315} INFO - Running statement: insert into weather(
                name
                -- temp,
                -- temp_min,
                -- temp_max,
                -- description,
                -- wind_speed,
                -- sunset,
                -- sunrise
            ) values (
                Краснодар
            ), parameters: None
[2022-09-03T11:25:20.263+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "Краснодар" does not exist
LINE 11:                 Краснодар
                         ^

[2022-09-03T11:25:20.274+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=weather_data, task_id=insert_weather_krd, execution_date=20220903T112514, start_date=20220903T112520, end_date=20220903T112520
[2022-09-03T11:25:20.284+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 149 for task insert_weather_krd (column "Краснодар" does not exist
LINE 11:                 Краснодар
                         ^
; 9922)
[2022-09-03T11:25:20.315+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-03T11:25:20.346+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
