[2022-09-03T11:32:39.633+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: weather_data.create_table manual__2022-09-03T11:32:37.489079+00:00 [queued]>
[2022-09-03T11:32:39.641+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: weather_data.create_table manual__2022-09-03T11:32:37.489079+00:00 [queued]>
[2022-09-03T11:32:39.643+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-03T11:32:39.645+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-03T11:32:39.647+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-03T11:32:39.659+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): create_table> on 2022-09-03 11:32:37.489079+00:00
[2022-09-03T11:32:39.665+0000] {standard_task_runner.py:52} INFO - Started process 10366 to run task
[2022-09-03T11:32:39.667+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_data', 'create_table', 'manual__2022-09-03T11:32:37.489079+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpriou7c26', '--error-file', '/tmp/tmp493tme4g']
[2022-09-03T11:32:39.669+0000] {standard_task_runner.py:80} INFO - Job 189: Subtask create_table
[2022-09-03T11:32:39.710+0000] {task_command.py:371} INFO - Running <TaskInstance: weather_data.create_table manual__2022-09-03T11:32:37.489079+00:00 [running]> on host 3d56073112d8
[2022-09-03T11:32:39.756+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-03T11:32:37.489079+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-03T11:32:37.489079+00:00
[2022-09-03T11:32:39.762+0000] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-09-03T11:32:39.765+0000] {sql.py:315} INFO - Running statement: create table if not exists weather(
                id          serial primary key,
                name        varchar(50),
                temp        float,
                temp_min    float,
                temp_max    float,
                description varchar(50),
                wind_speed  tinyint,
                sunset      smallint,
                sunrise     smallint
            ), parameters: None
[2022-09-03T11:32:39.767+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedObject: type "tinyint" does not exist
LINE 8:                 wind_speed  tinyint,
                                    ^

[2022-09-03T11:32:39.773+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=weather_data, task_id=create_table, execution_date=20220903T113237, start_date=20220903T113239, end_date=20220903T113239
[2022-09-03T11:32:39.779+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 189 for task create_table (type "tinyint" does not exist
LINE 8:                 wind_speed  tinyint,
                                    ^
; 10366)
[2022-09-03T11:32:39.801+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-03T11:32:39.827+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
