[2022-09-03T10:37:22.581+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: weather_data.check_weather manual__2022-09-03T10:37:18.374827+00:00 [queued]>
[2022-09-03T10:37:22.588+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: weather_data.check_weather manual__2022-09-03T10:37:18.374827+00:00 [queued]>
[2022-09-03T10:37:22.590+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-03T10:37:22.591+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-03T10:37:22.592+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-03T10:37:22.601+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): check_weather> on 2022-09-03 10:37:18.374827+00:00
[2022-09-03T10:37:22.605+0000] {standard_task_runner.py:52} INFO - Started process 7451 to run task
[2022-09-03T10:37:22.607+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_data', 'check_weather', 'manual__2022-09-03T10:37:18.374827+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp5gs646rw', '--error-file', '/tmp/tmpftxnm4_p']
[2022-09-03T10:37:22.609+0000] {standard_task_runner.py:80} INFO - Job 125: Subtask check_weather
[2022-09-03T10:37:22.661+0000] {task_command.py:371} INFO - Running <TaskInstance: weather_data.check_weather manual__2022-09-03T10:37:18.374827+00:00 [running]> on host 3d56073112d8
[2022-09-03T10:37:22.728+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data
AIRFLOW_CTX_TASK_ID=check_weather
AIRFLOW_CTX_EXECUTION_DATE=2022-09-03T10:37:18.374827+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-03T10:37:18.374827+00:00
[2022-09-03T10:37:22.742+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dag.py", line 18, in context_handler
    response = json.loads(ti.xcom_pull(task_ids='getting_weather'))
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2022-09-03T10:37:22.751+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=weather_data, task_id=check_weather, execution_date=20220903T103718, start_date=20220903T103722, end_date=20220903T103722
[2022-09-03T10:37:22.758+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 125 for task check_weather (the JSON object must be str, bytes or bytearray, not NoneType; 7451)
[2022-09-03T10:37:22.781+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-03T10:37:22.802+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
